# Generated by Django 4.2.11 on 2024-04-13 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unique_user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
