# Generated by Django 4.2.11 on 2024-04-14 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_loanapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
