# Generated by Django 4.2.11 on 2024-04-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_loanapplication_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_id',
        ),
    ]
