# Generated by Django 4.2.11 on 2024-04-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_loanapplication_id_loanapplication_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='myapp.user'),
        ),
    ]
