# Generated by Django 4.2.11 on 2024-04-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='amt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit_score',
        ),
    ]
